from enum import Enum, auto


class TokenType(Enum):
    EOF = auto()
    NEWLINE = auto()
    INDENT = auto()
    DEDENT = auto()
    IDENTIFIER = auto()
    NUMBER = auto()
    STRING = auto()
    NUT = auto()
    JAR = auto()
    CRUNCH = auto()
    OTHERWISE = auto()
    CHEW = auto()
    SPREAD = auto()
    IN = auto()
    PLUS = auto()
    MINUS = auto()
    STAR = auto()
    SLASH = auto()
    EQUAL = auto()
    EQUAL_EQUAL = auto()
    BANG_EQUAL = auto()
    GREATER = auto()
    LESS = auto()
    LPAREN = auto()
    RPAREN = auto()
    COLON = auto()
    COMMA = auto()
    IMPORT = auto()
    DOT = auto()